// Code generated by Kitex v0.5.0. DO NOT EDIT.
package accountservice

import (
	server "github.com/cloudwego/kitex/server"
	account "github.com/zxq97/design/weitter/account/kitex_gen/account"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler account.AccountService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
