// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID          int64     `gorm:"column:uid;not null" json:"uid"`
	Nickname     string    `gorm:"column:nickname;not null" json:"nickname"`
	Gender       int32     `gorm:"column:gender;not null;comment:0:为选 1:男 2:女" json:"gender"`   // 0:为选 1:男 2:女
	Introduction string    `gorm:"column:introduction;not null;comment:简介" json:"introduction"` // 简介
	Status       int32     `gorm:"column:status;not null;comment:0:正常 1:注销" json:"status"`      // 0:正常 1:注销
	Ctime        time.Time `gorm:"column:ctime;not null;default:CURRENT_TIMESTAMP" json:"ctime"`
	Mtime        time.Time `gorm:"column:mtime;not null;default:CURRENT_TIMESTAMP" json:"mtime"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
