// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cloudwego/kitex/server"
	"github.com/zxq97/design/weitter/like/service/internal/biz"
	"github.com/zxq97/design/weitter/like/service/internal/data"
	server2 "github.com/zxq97/design/weitter/like/service/internal/server"
	"github.com/zxq97/design/weitter/like/service/internal/service"
)

// Injectors from wire.go:

func initServer() server.Server {
	client := data.NewRedis()
	db := data.NewDB()
	syncProducer := data.NewKafkaProducer()
	likeRepo := data.NewLikeRepo(client, db, syncProducer)
	likeUseCase := biz.NewLikeUseCase(likeRepo)
	likeServiceImpl := service.NewLikeService(likeUseCase)
	serverServer := server2.NewKiteXServer(likeServiceImpl)
	return serverServer
}
