// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cloudwego/kitex/server"
	"github.com/zxq97/design/weitter/account/bff/internal/biz"
	"github.com/zxq97/design/weitter/account/bff/internal/data"
	server2 "github.com/zxq97/design/weitter/account/bff/internal/server"
	"github.com/zxq97/design/weitter/account/bff/internal/service"
)

// Injectors from wire.go:

func initServer() server.Server {
	client := data.NewAccountClient()
	accountBFFRepo := data.NewAccountBFFRepo(client)
	accountBFFUseCase := biz.NewAccountBFFUseCase(accountBFFRepo)
	accountBFFImpl := service.NewAccountBFF(accountBFFUseCase)
	serverServer := server2.NewKiteX(accountBFFImpl)
	return serverServer
}
