// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLikeCount = "like_count"

// LikeCount mapped from table <like_count>
type LikeCount struct {
	ID      int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ObjID   int64     `gorm:"column:obj_id;not null" json:"obj_id"`
	ObjType int32     `gorm:"column:obj_type;not null" json:"obj_type"`
	Count   int32     `gorm:"column:count;not null" json:"count"`
	Ctime   time.Time `gorm:"column:ctime;not null;default:CURRENT_TIMESTAMP" json:"ctime"`
	Mtime   time.Time `gorm:"column:mtime;not null;default:CURRENT_TIMESTAMP" json:"mtime"`
}

// TableName LikeCount's table name
func (*LikeCount) TableName() string {
	return TableNameLikeCount
}
