// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cloudwego/kitex/server"
	"github.com/zxq97/design/weitter/like/bff/internal/biz"
	"github.com/zxq97/design/weitter/like/bff/internal/data"
	server2 "github.com/zxq97/design/weitter/like/bff/internal/server"
	"github.com/zxq97/design/weitter/like/bff/internal/service"
)

// Injectors from wire.go:

func initServer() server.Server {
	client := data.NewLikeClient()
	accountbffClient := data.NewAccountClient()
	likeBFFRepo := data.NewLikeBFFRepo(client, accountbffClient)
	likeBFFUseCase := biz.NewLikeBFFUseCase(likeBFFRepo)
	likeBFFImpl := service.NewLikeBFF(likeBFFUseCase)
	serverServer := server2.NewKiteX(likeBFFImpl)
	return serverServer
}
