// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameArticle = "article"

// Article mapped from table <article>
type Article struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ArticleID int64     `gorm:"column:article_id;not null" json:"article_id"`
	UID       int64     `gorm:"column:uid;not null" json:"uid"`
	Content   string    `gorm:"column:content;not null" json:"content"`
	Ctime     time.Time `gorm:"column:ctime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"ctime"`   // 创建时间
	Mtime     time.Time `gorm:"column:mtime;not null;default:CURRENT_TIMESTAMP;comment:最近修改时间" json:"mtime"` // 最近修改时间
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
