// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cloudwego/kitex/server"
	"github.com/zxq97/design/weitter/archive/service/internal/biz"
	"github.com/zxq97/design/weitter/archive/service/internal/data"
	server2 "github.com/zxq97/design/weitter/archive/service/internal/server"
	"github.com/zxq97/design/weitter/archive/service/internal/service"
)

// Injectors from wire.go:

func initServer() server.Server {
	client := data.NewRedis()
	memcacheClient := data.NewMemCache()
	db := data.NewDB()
	syncProducer := data.NewKafkaProducer()
	archiveRepo := data.NewArchiveRepo(client, memcacheClient, db, syncProducer)
	archiveUseCase := biz.NewArchiveUseCase(archiveRepo)
	archiveServiceImpl := service.NewArchiveService(archiveUseCase)
	serverServer := server2.NewKiteXServer(archiveServiceImpl)
	return serverServer
}
