// Code generated by Kitex v0.5.0. DO NOT EDIT.

package accountbff

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	account "github.com/zxq97/design/weitter/kitex_gen/account"
	common "github.com/zxq97/design/weitter/kitex_gen/common"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateUser(ctx context.Context, req *account.CreateUserRequest, callOptions ...callopt.Option) (r *common.EmptyResponse, err error)
	GetUser(ctx context.Context, req *common.GetItemRequest, callOptions ...callopt.Option) (r *account.GetUserResponse, err error)
	MGetUsers(ctx context.Context, req *common.MGetItemARequest, callOptions ...callopt.Option) (r *account.MGetUsersResponse, err error)
	DeleteUsers(ctx context.Context, req *account.DeleteUsersRequest, callOptions ...callopt.Option) (r *common.EmptyResponse, err error)
	CheckAdminUser(ctx context.Context, req *common.GetItemRequest, callOptions ...callopt.Option) (r *common.CheckResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAccountBFFClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAccountBFFClient struct {
	*kClient
}

func (p *kAccountBFFClient) CreateUser(ctx context.Context, req *account.CreateUserRequest, callOptions ...callopt.Option) (r *common.EmptyResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUser(ctx, req)
}

func (p *kAccountBFFClient) GetUser(ctx context.Context, req *common.GetItemRequest, callOptions ...callopt.Option) (r *account.GetUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUser(ctx, req)
}

func (p *kAccountBFFClient) MGetUsers(ctx context.Context, req *common.MGetItemARequest, callOptions ...callopt.Option) (r *account.MGetUsersResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MGetUsers(ctx, req)
}

func (p *kAccountBFFClient) DeleteUsers(ctx context.Context, req *account.DeleteUsersRequest, callOptions ...callopt.Option) (r *common.EmptyResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUsers(ctx, req)
}

func (p *kAccountBFFClient) CheckAdminUser(ctx context.Context, req *common.GetItemRequest, callOptions ...callopt.Option) (r *common.CheckResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckAdminUser(ctx, req)
}
