// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/zxq97/design/fuxi/bff/internal/biz"
	"github.com/zxq97/design/fuxi/bff/internal/data"
	"github.com/zxq97/design/fuxi/bff/internal/server"
	"github.com/zxq97/design/fuxi/bff/internal/service"
)

// Injectors from wire.go:

func initApp() *kratos.App {
	client := data.NewRedis()
	db := data.NewDB()
	fuxiClient := data.NewFuxiClient()
	fuxiBFFRepo := data.NewFuxiBFFRepo(client, db, fuxiClient)
	fuxiBFFUseCase := biz.NewFuxiBFFUseCase(fuxiBFFRepo)
	fuxiBFFService := service.NewFuxiBFFService(fuxiBFFUseCase)
	grpcServer := server.NewGrpcServer(fuxiBFFService)
	httpServer := server.NewHttpServer(fuxiBFFService)
	app := newApp(grpcServer, httpServer)
	return app
}
